"""Export formatting — convert results to JSON, Markdown, and HTML."""

from __future__ import annotations

import importlib.resources
import json
from dataclasses import asdict, dataclass, field
from typing import Any

from markdown_it import MarkdownIt

# ── Markdown renderer (module-level singleton) ───────────────────────────────
# commonmark preset + table + strikethrough; html=False for XSS protection.
_md_renderer: MarkdownIt = MarkdownIt("commonmark", {"html": False}).enable(
    ["table", "strikethrough"]
)

# ── Tokyo Night dark-theme HTML template ─────────────────────────────────────
# Loaded once from vaig/ui/general_report_template.html (same pattern as
# html_report.py uses for spa_template.html).
# Single placeholder: {content} — the rendered HTML fragment.
_GENERAL_REPORT_TEMPLATE_CACHE: str | None = None


def _load_general_report_template() -> str:
    """Load general_report_template.html from the vaig.ui package, caching the result."""
    global _GENERAL_REPORT_TEMPLATE_CACHE
    if _GENERAL_REPORT_TEMPLATE_CACHE is None:
        _GENERAL_REPORT_TEMPLATE_CACHE = (
            importlib.resources.files("vaig.ui")
            .joinpath("general_report_template.html")
            .read_text(encoding="utf-8")
        )
    return _GENERAL_REPORT_TEMPLATE_CACHE


@dataclass(frozen=True, slots=True)
class ExportMetadata:
    """Metadata included in every export."""

    model: str
    skill: str | None
    timestamp: str
    tokens: dict[str, int]
    cost: str | None
    vaig_version: str


@dataclass
class ExportPayload:
    """Structured export data that can be serialized to any format."""

    question: str
    response: str
    metadata: ExportMetadata
    context_files: list[str] = field(default_factory=list)
    agent_results: list[dict[str, Any]] = field(default_factory=list)

    def to_json(self, *, indent: int = 2) -> str:
        """Serialize to JSON."""
        return json.dumps(asdict(self), indent=indent, ensure_ascii=False)

    def to_markdown(self) -> str:
        """Render as a Markdown report."""
        lines = [
            "# VAIG Analysis Report",
            "",
            f"**Model**: {self.metadata.model}  ",
        ]
        if self.metadata.skill:
            lines.append(f"**Skill**: {self.metadata.skill}  ")
        lines.append(f"**Date**: {self.metadata.timestamp}  ")
        if self.metadata.cost:
            lines.append(f"**Estimated Cost**: {self.metadata.cost}  ")
        tokens = self.metadata.tokens
        if tokens:
            lines.append(
                f"**Tokens**: {tokens.get('total_tokens', 0):,} total "
                f"({tokens.get('prompt_tokens', 0):,} prompt + "
                f"{tokens.get('completion_tokens', 0):,} completion)  "
            )
        lines.append("")

        # Question
        lines.extend(["## Question", "", self.question, ""])

        # Context files
        if self.context_files:
            lines.extend(["## Context Files", ""])
            for f in self.context_files:
                lines.append(f"- `{f}`")
            lines.append("")

        # Response
        lines.extend(["## Response", "", self.response, ""])

        # Agent results (for multi-agent)
        if self.agent_results:
            lines.extend(["## Agent Details", ""])
            for ar in self.agent_results:
                name = ar.get("agent_name", "unknown")
                content = ar.get("content", "")
                lines.extend([f"### {name}", "", content, ""])

        # Cost & Usage Summary section (detailed table at the end)
        cost_section = self._build_cost_summary_section()
        if cost_section:
            lines.append(cost_section)

        lines.extend(["---", f"*Generated by VAIG v{self.metadata.vaig_version}*"])
        return "\n".join(lines)

    def _build_cost_summary_section(self) -> str | None:
        """Build a ``## Cost & Usage Summary`` markdown section.

        Returns ``None`` if no meaningful token data is available.
        """
        tokens = self.metadata.tokens
        if not tokens:
            return None

        prompt_tokens = tokens.get("prompt_tokens", 0)
        completion_tokens = tokens.get("completion_tokens", 0)
        thinking_tokens = tokens.get("thinking_tokens", 0)
        total_tokens = tokens.get("total_tokens", 0)

        # Skip if everything is zero
        if total_tokens == 0 and prompt_tokens == 0 and completion_tokens == 0:
            return None

        lines = [
            "## Cost & Usage Summary",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Input tokens | {prompt_tokens:,} |",
            f"| Output tokens | {completion_tokens:,} |",
        ]

        if thinking_tokens:
            lines.append(f"| Thinking tokens | {thinking_tokens:,} |")

        lines.append(f"| Total tokens | {total_tokens:,} |")
        lines.append(f"| Model | {self.metadata.model} |")

        if self.metadata.cost:
            lines.append(f"| Estimated cost | {self.metadata.cost} |")

        lines.append("")
        return "\n".join(lines)

    def to_html(self) -> str:
        """Render as a self-contained HTML report using Tokyo Night dark theme.

        Converts the full ``to_markdown()`` output through ``markdown-it-py``
        (commonmark + table + strikethrough; HTML injection disabled) and
        wraps the fragment in the bundled ``general_report_template.html``.
        """
        md_content = self.to_markdown()
        html_fragment = _md_renderer.render(md_content)
        return _load_general_report_template().replace("{content}", html_fragment)


def format_export(
    payload: ExportPayload,
    fmt: str,
) -> str:
    """Format an export payload in the requested format.

    Args:
        payload: The structured export data.
        fmt: Format string — "json", "md"/"markdown", or "html".

    Returns:
        Formatted string content.

    Raises:
        ValueError: If the format is not recognized.
    """
    fmt = fmt.lower().strip()
    if fmt == "json":
        return payload.to_json()
    if fmt in ("md", "markdown"):
        return payload.to_markdown()
    if fmt == "html":
        return payload.to_html()
    msg = f"Unsupported export format: {fmt!r}. Use 'json', 'md', or 'html'."
    raise ValueError(msg)
