"""Export formatting — convert results to JSON, Markdown, and HTML."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from typing import Any


@dataclass(frozen=True, slots=True)
class ExportMetadata:
    """Metadata included in every export."""

    model: str
    skill: str | None
    timestamp: str
    tokens: dict[str, int]
    cost: str | None
    vaig_version: str


@dataclass
class ExportPayload:
    """Structured export data that can be serialized to any format."""

    question: str
    response: str
    metadata: ExportMetadata
    context_files: list[str] = field(default_factory=list)
    agent_results: list[dict[str, Any]] = field(default_factory=list)

    def to_json(self, *, indent: int = 2) -> str:
        """Serialize to JSON."""
        return json.dumps(asdict(self), indent=indent, ensure_ascii=False)

    def to_markdown(self) -> str:
        """Render as a Markdown report."""
        lines = [
            "# VAIG Analysis Report",
            "",
            f"**Model**: {self.metadata.model}  ",
        ]
        if self.metadata.skill:
            lines.append(f"**Skill**: {self.metadata.skill}  ")
        lines.append(f"**Date**: {self.metadata.timestamp}  ")
        if self.metadata.cost:
            lines.append(f"**Estimated Cost**: {self.metadata.cost}  ")
        tokens = self.metadata.tokens
        if tokens:
            lines.append(
                f"**Tokens**: {tokens.get('total_tokens', 0):,} total "
                f"({tokens.get('prompt_tokens', 0):,} prompt + "
                f"{tokens.get('completion_tokens', 0):,} completion)  "
            )
        lines.append("")

        # Question
        lines.extend(["## Question", "", self.question, ""])

        # Context files
        if self.context_files:
            lines.extend(["## Context Files", ""])
            for f in self.context_files:
                lines.append(f"- `{f}`")
            lines.append("")

        # Response
        lines.extend(["## Response", "", self.response, ""])

        # Agent results (for multi-agent)
        if self.agent_results:
            lines.extend(["## Agent Details", ""])
            for ar in self.agent_results:
                name = ar.get("agent_name", "unknown")
                content = ar.get("content", "")
                lines.extend([f"### {name}", "", content, ""])

        # Cost & Usage Summary section (detailed table at the end)
        cost_section = self._build_cost_summary_section()
        if cost_section:
            lines.append(cost_section)

        lines.extend(["---", f"*Generated by VAIG v{self.metadata.vaig_version}*"])
        return "\n".join(lines)

    def _build_cost_summary_section(self) -> str | None:
        """Build a ``## Cost & Usage Summary`` markdown section.

        Returns ``None`` if no meaningful token data is available.
        """
        tokens = self.metadata.tokens
        if not tokens:
            return None

        prompt_tokens = tokens.get("prompt_tokens", 0)
        completion_tokens = tokens.get("completion_tokens", 0)
        thinking_tokens = tokens.get("thinking_tokens", 0)
        total_tokens = tokens.get("total_tokens", 0)

        # Skip if everything is zero
        if total_tokens == 0 and prompt_tokens == 0 and completion_tokens == 0:
            return None

        lines = [
            "## Cost & Usage Summary",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Input tokens | {prompt_tokens:,} |",
            f"| Output tokens | {completion_tokens:,} |",
        ]

        if thinking_tokens:
            lines.append(f"| Thinking tokens | {thinking_tokens:,} |")

        lines.append(f"| Total tokens | {total_tokens:,} |")
        lines.append(f"| Model | {self.metadata.model} |")

        if self.metadata.cost:
            lines.append(f"| Estimated cost | {self.metadata.cost} |")

        lines.append("")
        return "\n".join(lines)

    def to_html(self) -> str:
        """Render as a self-contained HTML report."""
        import html as html_mod

        escaped = html_mod.escape(self.to_markdown())

        skill_html = ""
        if self.metadata.skill:
            skill_html = f"<p><strong>Skill</strong>: {html_mod.escape(self.metadata.skill)}</p>"

        cost_html = ""
        if self.metadata.cost:
            cost_html = f"<p><strong>Estimated Cost</strong>: {html_mod.escape(self.metadata.cost)}</p>"

        return (
            "<!DOCTYPE html>\n"
            '<html lang="en">\n'
            "<head>\n"
            '<meta charset="UTF-8">\n'
            '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
            "<title>VAIG Analysis Report</title>\n"
            "<style>\n"
            "  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;"
            " max-width: 800px; margin: 2rem auto; padding: 0 1rem; line-height: 1.6; color: #333; }\n"
            "  pre { background: #f6f8fa; padding: 1rem; border-radius: 6px; overflow-x: auto; }\n"
            "  code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }\n"
            "  .metadata { background: #f8f9fa; padding: 1rem; border-radius: 6px;"
            " margin-bottom: 1.5rem; border-left: 4px solid #0066cc; }\n"
            "  .metadata p { margin: 0.2rem 0; }\n"
            "  h1 { color: #0066cc; border-bottom: 2px solid #0066cc; padding-bottom: 0.5rem; }\n"
            "  h2 { color: #333; margin-top: 2rem; }\n"
            "  hr { border: none; border-top: 1px solid #ddd; margin: 2rem 0; }\n"
            "</style>\n"
            "</head>\n"
            "<body>\n"
            "<h1>VAIG Analysis Report</h1>\n"
            '<div class="metadata">\n'
            f"<p><strong>Model</strong>: {html_mod.escape(self.metadata.model)}</p>\n"
            f"{skill_html}\n"
            f"<p><strong>Date</strong>: {html_mod.escape(self.metadata.timestamp)}</p>\n"
            f"{cost_html}\n"
            "</div>\n"
            "<h2>Question</h2>\n"
            f"<p>{html_mod.escape(self.question)}</p>\n"
            "<h2>Response</h2>\n"
            f"<pre>{escaped}</pre>\n"
            "<hr>\n"
            f"<p><em>Generated by VAIG v{html_mod.escape(self.metadata.vaig_version)}</em></p>\n"
            "</body>\n"
            "</html>"
        )


def format_export(
    payload: ExportPayload,
    fmt: str,
) -> str:
    """Format an export payload in the requested format.

    Args:
        payload: The structured export data.
        fmt: Format string — "json", "md"/"markdown", or "html".

    Returns:
        Formatted string content.

    Raises:
        ValueError: If the format is not recognized.
    """
    fmt = fmt.lower().strip()
    if fmt == "json":
        return payload.to_json()
    if fmt in ("md", "markdown"):
        return payload.to_markdown()
    if fmt == "html":
        return payload.to_html()
    msg = f"Unsupported export format: {fmt!r}. Use 'json', 'md', or 'html'."
    raise ValueError(msg)
